name: Adopt-a-Drain
brand_name: Adopt-a-Drain
button_adopt: Adopt! #button.adopt
update_report: %{title} import (%{deleted_adopted_count} adopted %{things} removed, %{created_count} %{things} added, %{deleted_unadopted_count} unadopted %{things} removed)" #subjects.update_report
default_tagline: What does it mean to adopt a drain? #default.tagline
notices_adopted: You just adopted a drain #notices.adopted 
title_adopt: Adopt this drain
title_adopted:  This drain has been adopted
title_adopted_tagline: {count} drains adopted in %{city}
title_main: Adopt-a-Drain %{city}
sign_in: Sign in to adopt a drain
thank_you: Thank you for claiming this %{thing}!
title_email_text: I just adopted one of %{city}'s storm drains and pledged to help keep it clear of leaves and debris. You, too, can Adopt A Drain and help the City avoid flooding at %{root_url}."
title_tweet_text: Flooded streets aren't fun. I adopted my own %{city} storm drain at %{root_url}. Adopt and name yours.
title_description: You can adopt one of %{city}'s storm drains and pledge to help keep it clear of leaves and debris this rainy season. Lend a hand and help the City avoid flooding.
gis_icon_1: Unadopted
gis_icon_2: Adopted
gis_icon_3: In need of adoption
imperative: adopt
past_tense_verb: adopted
gerund: adopting